name: Hatongsu CI/CD

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      album: ${{ steps.filter.outputs.album }}
      gateway: ${{ steps.filter.outputs.gateway }}
      user: ${{ steps.filter.outputs.user }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            album:              
              - 'apps/album/**'
              - 'proto/**'
              - 'libs/**'
              - '.eslintrc.js'
              - 'nest-cli.json'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'tsconfig.json'
              - 'tsconfig.build.json'
            gateway:
              - 'apps/gateway/**'
              - 'proto/**'
              - 'libs/**'
              - '.eslintrc.js'
              - 'nest-cli.json'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'tsconfig.json'
              - 'tsconfig.build.json'
            user:
              - 'apps/user/**'
              - 'proto/**'
              - 'libs/**'
              - '.eslintrc.js'
              - 'nest-cli.json'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'tsconfig.json'
              - 'tsconfig.build.json'

  build-album:
    needs: changes
    if: ${{ needs.changes.outputs.album == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t zzingo5/hatongsu-album:$TIMESTAMP -f ./apps/album/Dockerfile --target production --push .

  build-gateway:
    needs: changes
    if: ${{ needs.changes.outputs.gateway == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t zzingo5/hatongsu-gateway:$TIMESTAMP -f ./apps/gateway/Dockerfile --target production --push .

  build-user:
    needs: changes
    if: ${{ needs.changes.outputs.user == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%S")" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t zzingo5/hatongsu-user:$TIMESTAMP -f ./apps/user/Dockerfile --target production --push .
